Feature/authentication modal
Dverybest/Eva-kitchen pull request #24
Opened 2021-07-24 22:24 UTC by NancyRike

2021-07-26 07:56 UTC, NancyRike commented
![Shipping](https://user-images.githubusercontent.com/60471771/126953559-d37ddd38-db5a-4ba2-872c-c0efdfc59f1f.PNG)

2021-07-26 20:41 UTC, Dverybest requested changes
Looks good, a little clean up required

2021-07-26 20:41 UTC, Dverybest commented on src/App.js
>  // import SignIn from './components/Authentication/signIn'
Remove used code and clean up comments

2021-07-26 20:41 UTC, Dverybest commented on src/App.js
>            {/* <Route exact path="/signIn" component={SignIn}/>
Remove

2021-07-26 20:41 UTC, Dverybest commented on src/components/Authentication/signIn.js
> +              {/* {props.isLoading?'Authenticating...':'Sign In'} */}
remove comment

2021-07-26 20:41 UTC, Dverybest commented on src/pages/CheckoutPage/checkoutPage.css
> +/* .imageWrapper{
remove unused code

2021-07-26 20:41 UTC, Dverybest commented on src/pages/CheckoutPage/checkoutPage.js
> +  // handlePageChange = (e, auth)=>{
Remove if not used

2021-07-27 02:54 UTC, NancyRike commented on src/pages/CheckoutPage/checkoutPage.js
> +  // handlePageChange = (e, auth)=>{
Fixed

2021-07-27 02:55 UTC, NancyRike commented on src/pages/CheckoutPage/checkoutPage.css
> +/* .imageWrapper{
Fixed

2021-07-27 02:55 UTC, NancyRike commented on src/components/Authentication/signIn.js
> +              {/* {props.isLoading?'Authenticating...':'Sign In'} */}
handled

2021-07-27 02:55 UTC, NancyRike commented on src/App.js
>            {/* <Route exact path="/signIn" component={SignIn}/>
fixed

2021-07-27 02:56 UTC, NancyRike commented on src/App.js
>  // import SignIn from './components/Authentication/signIn'
fixed

2021-07-27 06:56 UTC, Dverybest approved these changes

2021-07-27 06:56 UTC, merged