Feature for popular menu
Dverybest/Eva-kitchen pull request #4
Opened 2021-06-02 21:50 UTC by NancyRike

2021-06-03 12:44 UTC, Dverybest requested changes
Looks good to me, just a little clean of console.logs and commented out codes required

2021-06-03 12:44 UTC, Dverybest commented on src/pages/landingPage/LandingPage.js
> +    //         image: okroSoup,
Remove unused code commented out

2021-06-03 12:44 UTC, Dverybest commented on src/components/reusableMenuCard/Dish.js
> +// const mapStateToProps = (state)=>{
Remove unused commented out code

2021-06-03 12:44 UTC, Dverybest commented on src/components/reusableMenuCard/Dish.js
> +// import { connect } from 'react-redux';
Remove unused code commented out

2021-06-03 12:44 UTC, Dverybest commented on src/pages/landingPage/LandingPage.js
> +    console.log(props.popularMenuAction, "herehereHere");
Remove console.log

2021-06-03 12:44 UTC, Dverybest commented on src/pages/landingPage/LandingPage.js
> +    // console.log(popularMenu, 'looking for this');
Remove console.log

2021-06-03 12:44 UTC, Dverybest commented on src/reduxSetup/actions/popularMenuAction.js
> +        console.log("here?");
Remove console.log

2021-06-03 12:44 UTC, Dverybest commented on src/reduxSetup/actions/popularMenuAction.js
> +            console.log("you here?", response);
Remove console.log

2021-06-03 22:36 UTC, NancyRike commented on src/pages/landingPage/LandingPage.js
> +    console.log(props.popularMenuAction, "herehereHere");
resolved

2021-06-03 22:36 UTC, NancyRike commented on src/pages/landingPage/LandingPage.js
> +    // console.log(popularMenu, 'looking for this');
fixed

2021-06-03 22:37 UTC, NancyRike commented on src/reduxSetup/actions/popularMenuAction.js
> +        console.log("here?");
resolved

2021-06-03 22:38 UTC, NancyRike commented on src/components/reusableMenuCard/Dish.js
> +// import { connect } from 'react-redux';
this has been fixed

2021-06-03 22:39 UTC, NancyRike commented on src/reduxSetup/actions/popularMenuAction.js
> +            console.log("you here?", response);
this issue has been resolved

2021-06-04 07:20 UTC, NancyRike commented on src/pages/landingPage/LandingPage.js
> +    //         image: okroSoup,
resolved

2021-06-04 09:24 UTC, Dverybest approved these changes

2021-06-04 09:24 UTC, merged